### ISSUE TITLE
deno_mongo broken due to plugin_prepare@v0.3.1

### ISSUE THREAD

**Issue by slim-hmidi** [manyuanrong/deno-plugin-prepare#11]
I use [deno_mongov0.5.2](https://github.com/manyuanrong/deno_mongo) which use [deno-plugin-preparev0.3.1](https://github.com/manyuanrong/deno_mongo/blob/v0.5.2/deps.ts).
After the update of deno to v0.42.0, I got a lot of errors: 
```
error TS2367: This condition will always return 'false' since the types 'OperatingSystem' and '"windows"' have no overlap.

► https://deno.land/std/path/constants.ts:51:26

51 export const isWindows = build.os === "windows";
                            ~~~~~~~~~~~~~~~~~~~~~~

error TS2367: This condition will always return 'false' since the types 'OperatingSystem' and '"windows"' have no overlap.

► https://deno.land/std/path/globrex.ts:5:15

5 const isWin = Deno.build.os === "windows";
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~

error TS2345: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.

► https://deno.land/std/path/posix.ts:433:18

433   return new URL(url).pathname;
                     ~~~

error TS2339: Property 'get' does not exist on type '{ (): { [index: string]: string; }; (key: string): string | undefined; }'.

► https://deno.land/std/path/win32.ts:42:18

42       path = env.get(`=${resolvedDevice}`) || cwd();
                    ~~~

error TS2345: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.

► https://deno.land/std/path/win32.ts:911:18

911   return new URL(url).pathname
                     ~~~


Found 5 errors.

```
and I think it is due to imports in [mod.ts](https://github.com/manyuanrong/deno-plugin-prepare/blob/v0.3.1/mod.ts) are not tagged and it they use the latest version.

**Comment by eliassjogreen** [comment]
Plugins need to be run using the `--unstable` flag now as do many of the standard modules which has caused issues for me

**Comment by ronhippler** [comment]
could be closed. The current release (v0.6.0) fixes the issues.
